---
- name: REGISTER|join system to IDM
  include_tasks: join.yml
  when: ipaclient_state == "present"
  
- name: UNREGISTER|remove system from IDM
  include_tasks: remove.yml
  when: ipaclient_state == "absent"
